name: deploy-backend-on-main
description: Build + deploy backend Cloud Run service on merge to main.
serviceAccount: projects/health-fitness-160/serviceAccounts/tesseta-ci@health-fitness-160.iam.gserviceaccount.com
github:
  owner: gte619n
  name: tesseta
  push:
    branch: ^main$
filename: backend/cloudbuild.yaml
includedFiles:
  - backend/**
