name: deploy-web-on-main
description: Build + deploy web Cloud Run service on merge to main.
serviceAccount: projects/health-fitness-160/serviceAccounts/146599669983-compute@developer.gserviceaccount.com
github:
  owner: gte619n
  name: health-fitness-160
  push:
    branch: ^main$
filename: web/cloudbuild.yaml
includedFiles:
  - web/**
