name: deploy-web-on-main
description: Build + deploy web Cloud Run service on merge to main.
serviceAccount: projects/health-fitness-160/serviceAccounts/tesseta-ci@health-fitness-160.iam.gserviceaccount.com
github:
  owner: gte619n
  name: tesseta
  push:
    branch: ^main$
filename: web/cloudbuild.yaml
includedFiles:
  - web/**
